### ISSUE TITLE
NLP data visualization

### ISSUE THREAD

**Issue by breznak** [numenta-deprecated/nupic.fluent#170]
FYI https://github.com/nupic-community/nupic.visualizations/issues/5 
Btw, is this "the repo" for nupic NLP experiments/research?

**Comment by BoltzmannBrain** [comment]
@breznak no we've deprecated this repo and run our NLP research out of [nupic.research](https://github.com/numenta/nupic.research). Sorry for the confusion, I'll make this clear in the fluent readme.
