### ISSUE TITLE
Deprecate this repo!

### ISSUE THREAD

**Issue by BoltzmannBrain** [numenta-deprecated/nupic.fluent#171]
We've moved NLP research over to nupic.research. We should make this clear by either
- making this very clear in the fluent README
- deleting this repo
- other?

**Comment by BoltzmannBrain** [comment]
@subutai @scottpurdy @rhyolight what are your thoughts?

**Comment by subutai** [comment]
:+1: Or, should we just delete it?

**Comment by rhyolight** [comment]
No, I will deprecate it.

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by rhyolight** [comment]
https://github.com/numenta-deprecated
