### ISSUE TITLE
Python NLTK

### ISSUE THREAD

**Issue by BoltzmannBrain** [numenta-deprecated/nupic.fluent#47]
Investigate the [Python Natural Language Toolkit](http://www.nltk.org/). There may be useful components for fluent. Also they've assembled a [large set of NLP data corpora](http://www.nltk.org/nltk_data/).

**Comment by rhyolight** [comment]
I started trying to predict Parts of Speech here a long time ago.... didn't make it far but I felt there was some potential: https://github.com/numenta/nupic.nlp-examples/blob/master/run_pos_experiment.py
